export * from './clientes/components/Customers'
export * from './compras/ShoppingView'
export * from './cotizacion/Quotation'
export * from './reportes/Kardex'
export * from './ventas/SalesView'
export * from './home/Home'
export * from './garantia/Garantia'
export * from './separado/Separado'